Custom predictors
nasa/prog_server pull request #23
Opened 2024-02-09 23:23 UTC by kkannan7

Created a feature to accept custom predictors in prog_server. 
- The test code is written into integration.py
- The test code tries to use the Monte Carlo from progpy and succeeds

2024-02-10 01:12 UTC, teubert requested changes

2024-02-10 01:12 UTC, teubert commented on tests/integration.py
> +        prog_server.start(models={'ball': ball}, port=9883)
This doesn't test the new feature. We need to pass the predictor into start function like we do with model here.

Then when we create a session we have to tell it to use the new predictor (which is actually just a Monte Carlo)

2024-02-29 20:36 UTC, kjjarvis requested changes
This looks great. Nice addition. Just a few small adjustments and then I think it's ready

2024-03-01 00:15 UTC, kjjarvis reviewed
Great edits. One more suggestion - as per our conversation, let's add a test to check the TypeError that's in line 38 of prog_server

2024-03-27 21:30 UTC, kjjarvis approved these changes
Nice addition of custom predictors and corresponding tests

2024-03-27 21:30 UTC, merged